version: '2.4'

# Contains a tests runner container that is used to run the full test suite for
# the service against the test containers from `docker-compose.test.yml`.

services:
  tests-runner:
    build:
      context: .
      target: tests-runner
    volumes:
      - .:/opt/service:delegated
      - tests-runner-node-service-prototype/opt/service/node_modules
    environment:
      DEPLOY_ENVIRONMENT: ci
      SERVICE_HOST: test-node-service-prototype
      SERVICE_PORT: 9000
      POSTGRES_HOST: test-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DATABASE: test_db
    depends_on:
      test-node-service-prototype:
        condition: service_healthy

volumes:
  tests-runner-node-service-prototype:
