version: '2.4'

services:

  postgres:
    image: postgres:11.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rad_user
      POSTGRES_PASSWORD: rad_password
      POSTGRES_DB: rad_db
